apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.22.3
    version: 1.22.3
  name: gitea
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea