apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  type: ClusterIP
  ports:
    - port: <GITEA_EXTERNAL_PORT>
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitea
  namespace: gitea
subsets:
  - addresses:
      - ip: <GITEA_EXTERNAL_IP>
    ports:
      - port: <GITEA_EXTERNAL_PORT>