apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        revision: main # Use a specific tag of app-of-apps repository
        directories:
          - path: "clusters/*/*"
          - path: "clusters/*/infra"
            exclude: true
  template:
    metadata:
      name: "config-{{path[1]}}-{{path[2]}}-application"
      labels:
        env: "{{path[2]}}" 
        cluster: "{{path[1]}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        targetRevision: main # Use a specific tag of app-of-apps repository
        path: base/cluster/applications
        helm:
          values: |
            cluster_env: "{{path[2]}}" 
            cluster_name: "{{path[1]}}"
          valueFiles:
          - ../../../clusters/{{path[1]}}/{{path[2]}}/env-conf.yaml
          ignoreMissingValueFiles: true
      destination:
        name: "{{path[1]}}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - PrunePropagationPolicy=foreground