{{- if eq (include "isEnvDefined" .) "false" -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ .Values.cluster_name }}-infra-appset"
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        revision: main # Use a specific tag of app-of-apps repository
        files:
          - path: "clusters/{{ .Values.cluster_name }}/infra/*.yaml"
  template:
    metadata:
      name: "config-{{`{{infra.name}}`}}-application"
      labels:
        infra: "{{`{{infra.name}}`}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
      - repoURL: "{{`{{infra.repoURL}}`}}"
        targetRevision: "{{`{{infra.targetRevision}}`}}"
        path: "{{`{{infra.path}}`}}"
        helm:
          valueFiles:
          - values.yaml
          - $values/clusters/{{ .Values.cluster_name }}/cluster-conf.yaml
          - $values/clusters/{{ .Values.cluster_name }}/infra/{{`{{infra.name}}`}}.yaml
          ignoreMissingValueFiles: true
      - repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        targetRevision: main # Use a specific tag of app-of-apps repository
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{infra.namespace}}`}}"
      syncPolicy:
        {{- if .Values.argocd }}
        {{- if .Values.argocd.autoSync }}
        automated:
          prune: {{ .Values.argocd.prune }}
        {{- end }}
        {{- end }}
        syncOptions:
        - PrunePropagationPolicy=foreground
        - CreateNamespace=true
{{- end }}