apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        revision: main # Use a specific tag of app-of-apps repository
        directories:
          - path: "clusters/*"
  template:
    metadata:
      name: "config-{{path[1]}}-infra"
      labels:
        cluster: "{{path[1]}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        targetRevision: main # Use a specific tag of app-of-apps repository
        path: base/cluster/infra
        helm:
          values: |
            cluster_name: "{{path[1]}}"
          valueFiles:
          - ../../../clusters/{{path[1]}}/cluster-conf.yaml
          ignoreMissingValueFiles: true
      destination:
        name: "{{path[1]}}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - PrunePropagationPolicy=foreground