apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: docker-io-helm-oci
  namespace: argocd
stringData:
  url: registry-1.docker.io/bitnamicharts
  name: bitnamicharts
  type: helm
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: strimzi-helm-oci
  namespace: argocd
stringData:
  url: quay.io/strimzi-helm/strimzi-kafka-operator
  name: strimzi-kafka-operator
  type: helm
  enableOCI: "true"
