apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ .Values.cluster_name }}-{{ .Values.cluster_env }}-application-appset"
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        revision: main # Use a specific tag of app-of-apps repository
        files:
          - path: "clusters/{{ .Values.cluster_name }}/{{ .Values.cluster_env }}/applications/*.yaml"
  template:
    metadata:
      name: "config-{{ .Values.cluster_env }}-{{`{{application.name}}`}}-application"
      labels:
        application: "{{`{{application.name}}`}}"
        env: "{{ .Values.cluster_env }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
      - repoURL: "{{`{{application.repoURL}}`}}"
        targetRevision: "{{`{{application.targetRevision}}`}}"
        path: "{{`{{application.path}}`}}"
        chart: "{{`{{application.chart}}`}}"
        helm:
          valueFiles:
          - values.yaml
          - values-{{ .Values.cluster_env }}.yaml
          - $values/clusters/{{ .Values.cluster_name }}/{{ .Values.cluster_env }}/env-conf.yaml
          - $values/clusters/{{ .Values.cluster_name }}/{{ .Values.cluster_env }}/applications/{{`{{application.name}}`}}.yaml
          ignoreMissingValueFiles: true
      - repoURL: http://gitea.gitea.svc.cluster.local:3000/gitea_admin/app-of-apps.git
        targetRevision: main # Use a specific tag of app-of-apps repository
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{application.namespace}}`}}"
      syncPolicy:
        {{- if .Values.argocd }}
        {{- if .Values.argocd.autoSync }}
        automated:
          prune: {{ .Values.argocd.prune }}
        {{- end }}
        {{- end }}
        syncOptions:
        - PrunePropagationPolicy=foreground
        - CreateNamespace=true